### PR TITLE
Test Vbd_store using alcotest

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Iglói Gábor <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
I think the main Travis build will fail because there is a missing `{test}` dependency in xs-opam.

**Comment by mseri** [comment]
But alcotest is there https://github.com/xapi-project/xs-opam/tree/master/packages/upstream-extra/alcotest.0.7.2

I think it's an issue with camlcity server:
```
[ERROR] curl: code 502 while downloading
        http://download.camlcity.org/download/findlib-1.7.3.tar.gz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocamlfind.1.7.3
        (This may be fixed by running 'opam update')
```

**Comment by mseri** [comment]
Can you move the tests from `travis-opam` to `travis-docker`?

**Comment by gaborigloi** [comment]
Yep, I'll move it - as we discussed, `travis-opam` with OCaml 4.04 recompiles the compiler each time, thus it's a few minutes slower than `travis-docker`.

**Comment by mseri** [comment]
Tests are going to stay broken until `camlcity.org` is back online

**Comment by gaborigloi** [comment]
@mseri  Yaaaay camlcity is up and the test passes for some reason: https://travis-ci.org/xapi-project/xapi-nbd/builds/282198235
```
- Testing suite.

[OK]                Vbd_store          0   Add, remove, and load items.

- The full test results are available in `_build/_tests`.

- Test Successful in 0.004s. 1 test run.
```

**Review by mseri — APPROVED** [review]

**Pull request merged**
